local config = require("src.core.config")
local GameApi = require("src.utils.gameApi")
local constants = require("src.core.constants")
local score = GameApi.ScenEdit_GetScore(constants.SIDES.PLAYER)
GameApi.ScenEdit_SetScore(constants.SIDES.PLAYER, (score + config.s.ifv), "Landing successfully")
